spring.data.mongodb.uri=mongodb://localhost:27017/legal_ai_db

spring.application.name=legal-ai-backend
server.port=8080

ai.service.url=http://127.0.0.1:5000
app.jwt.secret=mySecretKey_ChangeThisLater_MustBe32CharsMin
app.jwt.expiration=86400000